name: QweTnts
version: '${project.version}'
main: ru.qweyns.qwetnts.QweTnts
api-version: '1.21'
folia-supported: true
author: qweyns
description: Кастомные динамиты поверх QweProtectStones (механика HolyWorld Lite)
depend:
  - QweProtectStones

commands:
  qwetnts:
    description: Администрирование кастомных динамитов
    usage: /<command> <reload|give|list>
    permission: qwetnts.admin
    aliases: [ qtnt, tnts ]

permissions:
  qwetnts.admin:
    description: Доступ к админ-командам /qtnt
    default: op
  qwetnts.use:
    description: Активация кастомных динамитов (если нет qwetnts.type.<id>)
    default: true
